### ISSUE TITLE
[Bug]: Todays alpha: Using the Toolkit "TestForm" shows that the drop button icon is not drawn

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1388]
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b4969b63-f48e-47ef-998c-90769260f331)

**Comment by giduac** [comment]
Hi @Smurf-IV 

Also KDropButton was affected by this and the change to ButtonValues.cs will make KDB behave the same as KButton.
PR underway.

**Comment by Smurf-IV** [comment]
@Wagnerp Should this go into 8.5 as well ?

**Comment by Wagnerp** [comment]
> @Wagnerp Should this go into 8.5 as well ?

@Smurf-IV Yes it should

**Comment by Smurf-IV** [comment]
@giduac Please recreate the change against the v85 branch and create a PR for that (Also include updates to the changelog)

**Comment by giduac** [comment]
@Smurf-IV 
Can I pop the same commits in there as in alpha ?

**Comment by Smurf-IV** [comment]
Yes, of course. (If they fit ;-))

**Comment by giduac** [comment]
@Smurf-IV 
PR posted: https://github.com/Krypton-Suite/Standard-Toolkit/pull/1503

**Comment by giduac** [comment]
Hi @Smurf-IV & @Wagnerp 

FYI.
In this fix there will several alterations. 
One of the problems with selecting themes are inconsistencies in the order of the `PaletteMode` `Enum` and the `PaletteModeStrings.SupprotedThemes` Dictionary.
This order will be corrected and the SupportedThemes order will be leading.

I would like to ask to make no changes to the two until this issue is complete.

This is the order of the two currently with the discrepancies between the two.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/414e1443-6417-4f62-accf-01b485d447ec)

**Comment by Smurf-IV** [comment]
I prefer the Right list, as it shows the "New" themes being added to the end of the list.
Alphabetical sorting can be done in the combo, as it will still (should) take the tag numbers for the offsets.

**Comment by Smurf-IV** [comment]
@giduac Also, remember that this has to be placed into 8.5, and still work in V90 without any changes to a designer made with V80 (i.e. enum offsets etc.)

**Comment by Smurf-IV** [comment]
A Bi Dectional map should take care of identifying what is what (They have been used for other "Sources of truth" as well)

**Comment by giduac** [comment]
> I prefer the Right list, as it shows the "New" themes being added to the end of the list. Alphabetical sorting can be done in the combo, as it will still (should) take the tag numbers for the offsets.
@Smurf-IV 
The right list will be leading as that is how thee Dictionary is created.

**Comment by giduac** [comment]
> A Bi-Directional map should take care of identifying what is what (They have been used for other "Sources of truth" as well)
@Smurf-IV 
The  PaletteMode enum is used a lot to retrieve the index and that is where things are out of sync atm.
Since the PaletteMode  starts with the Global entry the theme index is currently 1 off (if the order was correct).
Therefore PaletteMode will be started with a value of Global = -1.  And next the entry is the first theme which will receive the value `0`. Which is a valid index.

Also the three theme selector controls will be hooked up to the KManager change event so all stays in sync when a theme is changed from outside the theme selector controls.

I suggest to first make this for alpha and then we can see how much of that will fit in V85 or is desirable.

**Comment by giduac** [comment]
@Wagnerp 

Please close as this has been fixed and completed.
Thanks.
