### ISSUE TITLE
[Bug]: `KryptonContextMenuItemBase`: does not have a "Text" access API

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1672]
_Originally posted by 'Taner' on Discord_

Hello, I'm using old version (Krypton Suite - ComponentFactory) I just noticed, I can't set name property to `KryptonContextMenu` item. It's really hard to find which one is correct item while coding. Did someone say something about this problem? I know it's not getting any update anymore but I can't use the new version as comfortably as this one  it looks too complicated.

![image](https://github.com/user-attachments/assets/fbfe16c9-012e-4bb0-b9ed-8380f8a95095)

![image](https://github.com/user-attachments/assets/826ded71-7f68-4b9b-b837-34e856f578f1)

[sic] as you said it's version 4.5.9 but I just check newest version it's still same, `KryptonContextMenu` (items) don't have "Name" property even on latest version.

I leave here an example how I use it right now.

```vb
Dim checkBoxMappings As New Dictionary(Of String, KryptonContextMenuCheckBox)() From {
    {"H1", KryptonContextMenuCheckBox14},
    {"H1-2", KryptonContextMenuCheckBox15},
    {"H1-3", KryptonContextMenuCheckBox16},
    {"H1-4", KryptonContextMenuCheckBox17},
    {"H2", KryptonContextMenuCheckBox18},
    {"H2-2", KryptonContextMenuCheckBox19},
    {"H2-3", KryptonContextMenuCheckBox20},
    {"H2-4", KryptonContextMenuCheckBox21},
    {"H3", KryptonContextMenuCheckBox22},
    {"H3-2", KryptonContextMenuCheckBox23},
    {"H5", KryptonContextMenuCheckBox24},
    {"H7", KryptonContextMenuCheckBox25},
    {"H7-2", KryptonContextMenuCheckBox26},
    {"H8", KryptonContextMenuCheckBox27},
    {"H8-2", KryptonContextMenuCheckBox28},
    {"H9", KryptonContextMenuCheckBox29},
}
```

**Comment by TanerUNER** [comment]
I would like to add another information, when you want to access the .Text property while assigning a value to it, you cannot find the .Text property, but it works when you want to return this property. As you can see in the first picture. In the other picture, I am trying to find a different item, but as you can see, I can't access its .Text property. I don't think it would be a problem if there were a dozen items, but when there are dozens of them, it is almost impossible to find each item individually. You need to keep in mind that you can't find the order in which it is in a continuous array like 0-1-2 and set the “name” property.

![Adsız](https://github.com/user-attachments/assets/f63ab6bd-4755-4e47-b90e-1a37aec4824e)
![Adsız2](https://github.com/user-attachments/assets/2facc415-6b19-45f6-bd87-0efcdbd5eff4)

**Comment by Smurf-IV** [comment]
@TanerUNER Thanks for the in depth research;
But..
The `Items` is a list of `KryptonBaseItems`. Which is an abstract class for things menu. Some of these "Like a `separator` do not have `Text` field, and therefore are not part of the abstract class.
`.Net basic` has done "some magic" in reflection in the background and turned the abstract class at runtime into a something that can return the text field because Item(0) just happens to have "One of those" for that object instance.

This knowledge, allows you to perform some workaround.

Now, in Winforms, the `ToolStripSeparator` _does_ have an `override string Text` API !

So this "Bug" is to add the same override to the abstract base class ;-)
This is what will be "Fixed" in v90.
