### ISSUE TITLE
[Feature Request]: Proper support for a 'browse/open' button spec type

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1876]
Proper support for a 'browse/open' button spec type, rather than having 

![image](https://github.com/user-attachments/assets/d24cbc62-ff1d-4f8a-9fbb-3a58bf54c8c8)

**Comment by Smurf-IV** [comment]
Can you give an example?
And how would this be solved with theming ?

**Comment by PWagner1** [comment]
> Can you give an example? And how would this be solved with theming ?

Rather than use '...', use the 'open folder' icon instead

![image](https://github.com/user-attachments/assets/0efcd308-777a-478c-885f-ca868653bcdf)

**Comment by giduac** [comment]
It should remain open to the dev which imagery to use
This gets to specific imo....

**Comment by Smurf-IV** [comment]
Hmm, My $0.02:
I think it is a developer choice, and would be driven by a UX person. 
Defaulting to that icon would not "Fit in" for some apps that are using vector icons anyway!
and the "`...`" was always classed as _"action would open another window"_ and that's why it is used in Menu strings etc.

**Comment by Smurf-IV** [comment]
@PWagner1 Can this be closed now ?
