### ISSUE TITLE
[Bug]: DataGridView doesn't show Tooltip on Header Column (Column; 0)

### ISSUE THREAD

**Issue by Nordlien** [Krypton-Suite/Standard-Toolkit#445]
**Describe the bug**
DataGridView doesn't show Tooltip on Header Column (Column; 0)

**How to fix the issue**

Copy of the code:
private void CellDataAreaMouseEnterInternal(DataGridViewCell cell)
        {
            Point currentCellAddress = CurrentCellAddress;

            //Just remove the line below, that check if Row or Column, then it works: 
            // if (!((cell.RowIndex >= 0) && (cell.ColumnIndex == -1)))

**Comment by Smurf-IV** [comment]
I wonder if the original intention was to have a different tooltip for the headers ?

**Comment by Nordlien** [comment]
When I did this changes it works with Krypton Tooltip on headers. Without changes none of tooltip works for headers

**Comment by Smurf-IV** [comment]
Unable to reproduce this.

![image](https://user-images.githubusercontent.com/2418812/141677951-74360013-c248-43ce-9392-c2d2e9eee097.png)

Caused by hovering over the DateTime column header:
![image](https://user-images.githubusercontent.com/2418812/141677973-6bc7b65a-0049-4661-a601-ae2b7d058667.png)

**Comment by Smurf-IV** [comment]
Please see the code that is attached to the PR above.
