### ISSUE TITLE
[Feature Request]: ToolStrip embedded into the non client area

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#602]
Is it possible to implement something like this? https://www.codeproject.com/Articles/32623/Vista-Aero-ToolStrip-on-Non-Client-Area

![image](https://user-images.githubusercontent.com/949607/149980682-e864e79c-7cca-4e77-9d65-0708e91b48cd.png)

**Comment by Wagnerp** [comment]
Note: @Giduac on Discord has stated:

"There's some part of it in KT (source) `Krypton Components\Krypton.Toolkit\General\DesktopWindowManager.cs`"

**Comment by giduac** [comment]
Hi there,

@Wagnerp @Smurf-IV 
The above which in KT is only a little that is needed.

I downloaded the demo project from the Codeproject link you posted (see attachment).
Still need to go through it to see how this works exactly.

This MS API Document can be of use since these functions belong to the Dwm Api:
[](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/)

On Win 8.1 / Win 10 / Win 11 this demo works well.
On Win7 Ultimate SP1 Build: 7601 it does not work consistently, see video.

The system menu gets obscured by the toolstrip but remains functional. It can be invoked by the keyboard combo ALT+SPACE.
Right click on the taskbar button.

Cheers,


https://user-images.githubusercontent.com/96108132/150496039-704869c4-7f2c-41a0-94d0-0b4a5360d8bb.mp4


[aerononclientbuttons.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7911780/aerononclientbuttons.zip)

**Comment by Smurf-IV** [comment]
The "aerononclientbuttons.zip" seems to be wanting to do the QAT style buttons without the QAT round button.
That should already be possible without any code modification to the toolkit, due to the fact that the QAT buttons are a separate control **but* do need "currently" a ribbon bar to work (Which could be locked closed):
![image](https://user-images.githubusercontent.com/2418812/153558419-6458e282-9ab6-400a-8de0-5cea156e0759.png)

**Comment by giduac** [comment]
> The "aerononclientbuttons.zip" seems to be wanting to do the QAT style buttons without the QAT round button. That should already be possible without any code modification to the toolkit, due to the fact that the QAT buttons are a separate control *_but_ do need "currently" a ribbon bar to work (Which could be locked closed): ![image](https://user-images.githubusercontent.com/2418812/153558419-6458e282-9ab6-400a-8de0-5cea156e0759.png)

A toolstrip has a wider variety of controls to choose from. Including the ToolStripControlHost to nest (Krypton)Winforms controls. QAT Buttons has as far as I can see only buttons which makes it a more limited option.

**Comment by Smurf-IV** [comment]
Some functionality is now available with left aligned ButtonSpecs due to changes in #646 
And reflects usage from the original image Feature request image.

**Comment by Wagnerp** [comment]
Done, as part of v80
