### ISSUE TITLE
[Bug]: KryptonTextBox `Validate` / `Validating` / `KeyUp` events are invoked twice

### ISSUE THREAD

**Issue by overlinejota** [Krypton-Suite/Standard-Toolkit#666]
A simple form with a KrytonTextBox and a button.
The next code wave twice when KryptoTextbox1 loses focus:

```
namespace AppForm{
    public partial class Form1 : Krypton.Toolkit.KryptonForm{
        public Form1() {
            InitializeComponent();
        }            
        private void kryptonTextBox1_Validated(object sender, EventArgs e) {
            MessageBox.Show("Error","Hello");
        }
    }
}

private void InitializeComponent() {
	...
	this.kryptonTextBox1.Validated += new System.EventHandler(this.kryptonTextBox1_Validated);
	...
}

```
Thanks;

**Comment by giduac** [comment]
KMaskedTextbox is also affected.
Also  happens with the "Validating" event.

**Comment by Wagnerp** [comment]
@Smurf-IV Is this linked to the fixes that were merged yesterday?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is this linked to the fixes that were merged yesterday?

Do not think so, Did not look at any impact in this area as I was in the Dock and ribbon projects

**Comment by Wagnerp** [comment]
> > @Smurf-IV Is this linked to the fixes that were merged yesterday?
> 
> Do not think so, Did not look at any impact in this area as I was in the Dock and ribbon projects

Is this just missing the 'Focus()' call in the validate event?

**Comment by thiagoraheem** [comment]
I have the same situation and I created a project to demonstrate

https://github.com/thiagoraheem/KryptonTest

**Comment by Smurf-IV** [comment]
This also affects other controls like `KDomainUD`

It is because 
- the Kyrpton `VisualControlBase` is based on the winforms `Control`
- When "Adding" an event in the designer, it adds to the direct `Validated` EventHandler
- Inside Krypton it also has added an EventHandler to the control it is wrapping.
- The Krypton EventHandler calls the base controls `On#####()` version, thus triggering it twice.

This could take a while to fix, e.g. just "some" of the eents in the KDominUD:
``` c#
        private void OnDomainUpDownTextChanged(object sender, EventArgs e) => OnTextChanged(e);

        private void OnDomainUpDownScroll(object sender, ScrollEventArgs e) => OnScroll(e);

        private void OnDomainUpDownSelectedItemChanged(object sender, EventArgs e) => OnSelectedItemChanged(e);

        private void OnDomainUpDownGotFocus(object sender, EventArgs e)
        {
            UpdateStateAndPalettes();
            PerformNeedPaint(true);
            InvalidateChildren();
            base.OnGotFocus(e);
        }

        private void OnDomainUpDownLostFocus(object sender, EventArgs e)
        {
            UpdateStateAndPalettes();
            PerformNeedPaint(true);
            InvalidateChildren();
            // ReSharper disable RedundantBaseQualifier
            base.OnLostFocus(e);
            // ReSharper restore RedundantBaseQualifier
        }

        private void OnDomainUpDownKeyPress(object sender, KeyPressEventArgs e) => OnKeyPress(e);

        private void OnDomainUpDownKeyUp(object sender, KeyEventArgs e) => OnKeyUp(e);

        private void OnDomainUpDownKeyDown(object sender, KeyEventArgs e) => OnKeyDown(e);

        private void OnDomainUpDownPreviewKeyDown(object sender, PreviewKeyDownEventArgs e) => OnPreviewKeyDown(e);

        private void OnDomainUpDownValidated(object sender, EventArgs e) => OnValidated(e);

        private void OnDomainUpDownValidating(object sender, CancelEventArgs e) => OnValidating(e);
```

Q: Should the `OnDomainUpDownGotFocus` be rewritten to not call the base class, because it will end up calling it twice ?
A: Maybe; who knows for each Krypton control !!

**Comment by Wagnerp** [comment]
I was going round in circles for months trying to track down this bug!

@Smurf-IV What happens if you "disable" Krypton's implementation & use the standard WinForms validation calls?

**Comment by Smurf-IV** [comment]
> @Smurf-IV What happens if you "disable" Krypton's implementation & use the standard WinForms validation calls?

It will work as expected..
It's just all the the other event handlers that will need consideration !
Trouble is when Krypton needs to do something with the event and then calls the base anyway..

**Comment by Smurf-IV** [comment]
Update: Darn it.. Keep going round in circles when trying to apply to all Krypton controls.. This bug is entrenched too deeply in some places, and I haven't even moved into Ribbons yet !

**Comment by Smurf-IV** [comment]
I'm going to focus on just this control, so that it can be validated by @overlinejota as soon as a fix is published.
Otherwise there would be too many controls updated tat would remain untested fro a long time.
@Wagnerp will need something on the landing page asking for instances of "Double events" to be raised ASAP so that they can be worked on in turn with active users ready to "Test" the result.

![image](https://user-images.githubusercontent.com/2418812/175770957-1149844a-3b59-4266-94ed-00e6760d29a0.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Ok, will broadcast a message out on Discord too

**Comment by Smurf-IV** [comment]
FYI: Reason for separate controls updates;
![image](https://user-images.githubusercontent.com/2418812/175771356-641569c7-d567-47ea-bb79-9c48d54a816a.png)

In the above by just "Removing things that just call through to the base" shows the the click events are no longer working in the `KryptonTextBox`

**Comment by Smurf-IV** [comment]
Done, with a few other events as well:
![TBClickValidate](https://user-images.githubusercontent.com/2418812/175771973-b3550c9a-583a-43e8-826d-ee6a9c4f3ae0.gif)

 PR coming soon
