### ISSUE TITLE
[Bug]: No design support while using Krypton.Ribbon in .NET 5/6

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#71]
There is no designer support while using `Krypton.Ribbon` in .NET 5/6 projects.

**Comment by Smurf-IV** [comment]
FYI:
They are loaded, just not visible to be used in the Ribbon projects..
Something is _screwing_ with the designer (Alls of them) because even the toolkit is not enabled
i..e Right click in "Toolbox" and select "Show All!

![image](https://user-images.githubusercontent.com/2418812/118361772-c1671180-b584-11eb-9e08-e724e52d3b9a.png)

**Comment by Smurf-IV** [comment]
With the fixes and workaround mentioned here:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/92#issuecomment-841670257

It is possible to use the Ribbon toolbox in the forms designer again:
![image](https://user-images.githubusercontent.com/2418812/118365632-7dc8d380-b595-11eb-855b-ac5506505dd5.png)

**Comment by Smurf-IV** [comment]
Available August 2021 (Canary)
