### ISSUE TITLE
[Bug]: KryptonTextBox does not show text then on setting UseSystemPasswordChar to True

### ISSUE THREAD

**Issue by ZXBITLES** [Krypton-Suite/Standard-Toolkit#775]
**Describe the bug**
KryptonTextBox does not show text then on setting UseSystemPasswordChar to True

**To Reproduce**
Set UseSystemPasswordChar to True and define PasswordChar.
In runtime change UseSystemPasswordChar to False.
Text will be not shown.

**Expected behavior**
Text should be shown on changing UseSystemPasswordChar to False.

**Comment by Smurf-IV** [comment]
This occurs when **NO** char is set in the `PasswordChar` 
![image](https://user-images.githubusercontent.com/2418812/179348936-08bc0b47-e42d-45b2-b324-5071f838368f.png)

Because setting the `UseSystemPasswordChar to False` expects a value to _then_ be set for the `PasswordChar`
![image](https://user-images.githubusercontent.com/2418812/179348985-7578b608-2511-4cae-a5fc-6d8614c0c35e.png)

Setting to true after false does reset to the system default:
![image](https://user-images.githubusercontent.com/2418812/179349008-321e4892-d4a2-4775-b740-ecf682942599.png)
