### ISSUE TITLE
[Bug]: Unable to Set KColorButton Image

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#792]
Using Visual Studio 2022, NET6 designer, and Krypton Toolkit Nightly 70.22.8.213. This also occurs in stable version 6.2201.4, so I assume its an issue with VS2022 and NET 6 designer. Not targeting multiple frameworks for designer due to incompatible Nuget packages.

Cannot set the image via designer or programatically for Krypton Color Button. In VS2019 the button would look like the image below, and would only show the image if the color was set to transparent.

![image](https://user-images.githubusercontent.com/1911567/182451194-59861f42-d15a-464f-9051-e409e46631dd.png)

Now the button looks like this and cannot be changed.

![image](https://user-images.githubusercontent.com/1911567/182451310-12de6453-1524-4976-9185-1aa18a1733c0.png)

Regardless of what image is selected in the designer, the designer code always resets to this:

this.btnImageColor.Values.Image = ((System.Drawing.Image)(resources.GetObject("btnImageColor.Values.Image")));

**Comment by Smurf-IV** [comment]
Colour me confused (See what I did there.. ;-))

In the example it colours a box dependent on the colour choson:
![image](https://user-images.githubusercontent.com/2418812/198877561-dc30b0a5-f8b7-44dd-8343-5d86b13492a2.png)

What are you trying to do?, because the colour thing that you have in the 2nd image looks like the font dialog button ?

**Comment by sdreb3421** [comment]
I'm not sure anymore. Took me an hour to make my own color button so I just went that route.
