### ISSUE TITLE
[Bug]: Unable to detect when a `KrytponPage` instance is closing

### ISSUE THREAD

**Issue by wiredwiz** [Krypton-Suite/Standard-Toolkit#803]
In my project, the KryptonDockingManager.PageCloseRequest event fires when I undock a document window then click the close button on the floating document window.  However, if I click the close button on a docked document window and or use the context menu to close the tab, the event never fires for any closed pages.  I do not understand why this is.  I have been digging thought the source and using breakpoints to diagnose behavior but I have yet to find a reason for this.  I use the following close in my form load event when the app initializes
```
        // Setup docking functionality
        Workspace = kryptonDockingManager.ManageWorkspace(kryptonDockableWorkspace);
        kryptonDockingManager.ManageControl("Control1", kryptonPanel);
        kryptonDockingManager.ManageFloating(this);

        kryptonDockingManager.AddDockspace("Control1", DockingEdge.Bottom, new KryptonPage[] { NewErrorDisplay() });
```
Then later when document windows are created, I generate a new KrytponPage with the appropriate control and use the following code to add it to my workspace: `kryptonDockingManager.AddToWorkspace("Workspace", new KryptonPage[] { page });`

If there is something I am missing, I would love to know.  I cannot make heads or tails as to why the event fires for floating document windows but not for docked ones.

**Comment by Smurf-IV** [comment]
My thoughts (And a brief investigation)
- pages are stored in a Navigator
- Navigator close buttonSpec is clicked
- `OnClick` in `ButtonController` is fired
- routed through to `PerformClick` -> `OnClick` -> 
![image](https://user-images.githubusercontent.com/2418812/192138386-3b1dd5f6-29d4-4b45-b946-e760268f4524.png)
- eventually it gets to 
![image](https://user-images.githubusercontent.com/2418812/192138424-52c48b2c-f37c-4435-8909-4c831b25c53b.png)
in `KryptonSpace`

The problem is, that this is normally null.
So to get it to be "Handled" by your code you will need to add an event handler.
The following code is modified fro the "Standard Docking 2022" example `form.cs`, and it shows the close being "caught"
![image](https://user-images.githubusercontent.com/2418812/192138522-39e01dbe-fa60-4c4e-b639-7ff5e45bb7c9.png)

**Comment by wiredwiz** [comment]
Thank you, the explanation is greatly appreciated.
