### ISSUE TITLE
[Bug]: KryptonDataGridView doesn't call the 'paint' method of  Custom DataGridViewColumnHeaderCell

### ISSUE THREAD

**Issue by HardToFail** [Krypton-Suite/Standard-Toolkit#860]
As you can see,DatagridViewCheckBoxHeaderCell is a custom DataGridViewColumnHeaderCell ,it is Inherited from DataGridViewColumnHeaderCell.I have rewrited the 'paint' method. In this method , I can get a  ColumnHeaderCell with a checkbox.
![image](https://user-images.githubusercontent.com/118651630/206341446-ec2bf885-1046-45e4-8baa-f6ae9a33a9e3.png)

Then when I try to use it in my form,I have noticed that KryptonDataGridView doesn't call the 'print' method of  Custom DataGridViewColumnHeaderCell but DataGridView can.
![image](https://user-images.githubusercontent.com/118651630/206342283-c914c85a-ce2e-4c41-b282-caa67c4c0238.png)

![image](https://user-images.githubusercontent.com/118651630/206342553-26229084-7109-48be-9b7e-6400841629ad.png)

**Comment by Smurf-IV** [comment]
KDataGridView has no concept of a "Separate Header cell" type.
In order to do what you require I suggest (AS a workaround) to derive from KDataGridView and then override the following to perform drawing of the header you require when it is encountered:
![image](https://user-images.githubusercontent.com/2418812/206853587-7ffc37ec-ca71-423b-9bb0-0371d61a82b6.png)
(i.e. add your checkbox at an appropriate place after the theming has ben done)

I think the reasoning for "Not a separate type", is down to maintaining a consistent "Theme" experience, i.e. all drawing os done at the grid view level rather than having to shell out to a derived header.

**Comment by Smurf-IV** [comment]
@HardToFail Can this be closed now ?
