### ISSUE TITLE
[Question/Discussion]: Do we drop support for certain versions of products for v80?

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#862]
Just wondering, do we drop support for certain versions of products for v80? For example, Windows 7, 8 & 8.1 along with .NET Core 3.1 & .NET 5 (maybe).

**Comment by Smurf-IV** [comment]
My 2c''s:
- Win 7++ - No, still a lot of dev updates going on those.
- Core 3.1 - No, due to early adopters setting on that code base and then releasing (Same as Win 7 arguments)
- Net 5 - Yes, it was always going to be an interim release, that's why MS gave it a short support cycle, and net 6 is a droppin replacement (with the same designer problems ;-()

**Comment by Smurf-IV** [comment]
This text will need to change - whatever happens
![image](https://user-images.githubusercontent.com/2418812/206893276-78efc1da-e22d-4a9a-ba2d-e316d4ddbcba.png)

**Comment by Wagnerp** [comment]
I think dropping support for interim releases when they're EOL is a good idea, as it'll reduce the size of the packages. Will remove NET 5 this week

**Comment by Smurf-IV** [comment]
Can you add to the OP, when V80 is expected to be released please ?

**Comment by Wagnerp** [comment]
Yes, sure I'll update the documents in the documentation repo

**Comment by Smurf-IV** [comment]
> Yes, sure I'll update the documents in the documentation repo

Place a link in here, then this can be closed (I think ??)

**Comment by Wagnerp** [comment]
> > Yes, sure I'll update the documents in the documentation repo
> 
> Place a link in here, then this can be closed (I think ??)

https://github.com/Krypton-Suite/Documentation/blob/main/Documents/Development/Package-Support-Information.md
