### ISSUE TITLE
[Bug]: PagesWorkspace

### ISSUE THREAD

**Issue by SmartSuperAppSuperApp** [Krypton-Suite/Standard-Toolkit#897]
PagesWorkspace.Length incorrect calculation when closing all pages in Krypton.Docking with ActivePageChanged event

**Comment by Smurf-IV** [comment]
@SmartSuperAppSuperApp 
Sorry. this slipped through the gap, do you have a small demoapp, or do one of the existing toolkit demos demonstrate this ?

**Comment by giduac** [comment]
Hi @SmartSuperAppSuperApp, @Wagnerp 

I can't find a property Length. 

The Count properties return the correct values.
```cs
            KryptonWorkspace.CellCount
            KryptonWorkspace.CellVisibleCount
            KryptonWorkspace.PageCount
            KryptonWorkspace.PageVisibleCount
```

Since you didn't react to our earlier request for additional information, we will close this ticket.
If you like it reopened please let us know.

@Wagnerp 
I suggest to close this ticket due to in activity.
